
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DEF FUNC LB LBK LP PARAGRAPH RB RBK RP SEP STAR TEXT UNDER VARstart : start one_def\n             | start reg_bloc\n             | one_def : DEF FUNC LP SEP RP LB smd RBsmd : smd reg_bloc\n           | reg_blocreg_bloc : TEXT\n                | STAR in_bold_italic STAR\n                | UNDER in_bold_italic UNDER\n                | LBK smd RBK\n                | PARAGRAPH\n                | FUNC LB smd RB\n                | VARin_bold_italic : TEXT\n                      | LBK smd RBK\n                      | PARAGRAPH\n                      | FUNC LB smd RB\n                      | VAR'
    
_lr_action_items = {'DEF':([0,1,2,3,6,10,11,25,28,29,32,39,],[-3,4,-1,-2,-7,-11,-13,-8,-9,-10,-12,-4,]),'TEXT':([0,1,2,3,6,7,8,9,10,11,13,16,21,22,24,25,26,27,28,29,30,32,34,37,38,39,],[-3,6,-1,-2,-7,15,15,6,-11,-13,6,6,6,-6,6,-8,6,6,-9,-10,-5,-12,6,6,6,-4,]),'STAR':([0,1,2,3,6,9,10,11,13,14,15,16,17,19,21,22,24,25,26,27,28,29,30,32,33,34,36,37,38,39,],[-3,7,-1,-2,-7,7,-11,-13,7,25,-14,7,-16,-18,7,-6,7,-8,7,7,-9,-10,-5,-12,-15,7,-17,7,7,-4,]),'UNDER':([0,1,2,3,6,9,10,11,13,15,16,17,19,20,21,22,24,25,26,27,28,29,30,32,33,34,36,37,38,39,],[-3,8,-1,-2,-7,8,-11,-13,8,-14,8,-16,-18,28,8,-6,8,-8,8,8,-9,-10,-5,-12,-15,8,-17,8,8,-4,]),'LBK':([0,1,2,3,6,7,8,9,10,11,13,16,21,22,24,25,26,27,28,29,30,32,34,37,38,39,],[-3,9,-1,-2,-7,16,16,9,-11,-13,9,9,9,-6,9,-8,9,9,-9,-10,-5,-12,9,9,9,-4,]),'PARAGRAPH':([0,1,2,3,6,7,8,9,10,11,13,16,21,22,24,25,26,27,28,29,30,32,34,37,38,39,],[-3,10,-1,-2,-7,17,17,10,-11,-13,10,10,10,-6,10,-8,10,10,-9,-10,-5,-12,10,10,10,-4,]),'FUNC':([0,1,2,3,4,6,7,8,9,10,11,13,16,21,22,24,25,26,27,28,29,30,32,34,37,38,39,],[-3,5,-1,-2,12,-7,18,18,5,-11,-13,5,5,5,-6,5,-8,5,5,-9,-10,-5,-12,5,5,5,-4,]),'VAR':([0,1,2,3,6,7,8,9,10,11,13,16,21,22,24,25,26,27,28,29,30,32,34,37,38,39,],[-3,11,-1,-2,-7,19,19,11,-11,-13,11,11,11,-6,11,-8,11,11,-9,-10,-5,-12,11,11,11,-4,]),'$end':([0,1,2,3,6,10,11,25,28,29,32,39,],[-3,0,-1,-2,-7,-11,-13,-8,-9,-10,-12,-4,]),'LB':([5,18,35,],[13,27,37,]),'RBK':([6,10,11,21,22,25,26,28,29,30,32,],[-7,-11,-13,29,-6,-8,33,-9,-10,-5,-12,]),'RB':([6,10,11,22,24,25,28,29,30,32,34,38,],[-7,-11,-13,-6,32,-8,-9,-10,-5,-12,36,39,]),'LP':([12,],[23,]),'SEP':([23,],[31,]),'RP':([31,],[35,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'one_def':([1,],[2,]),'reg_bloc':([1,9,13,16,21,24,26,27,34,37,38,],[3,22,22,22,30,30,30,22,30,22,30,]),'in_bold_italic':([7,8,],[14,20,]),'smd':([9,13,16,27,37,],[21,24,26,34,38,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> start one_def','start',2,'p_start','PLY',161),
  ('start -> start reg_bloc','start',2,'p_start','PLY',162),
  ('start -> <empty>','start',0,'p_start','PLY',163),
  ('one_def -> DEF FUNC LP SEP RP LB smd RB','one_def',8,'p_one_def','PLY',167),
  ('smd -> smd reg_bloc','smd',2,'p_smd','PLY',171),
  ('smd -> reg_bloc','smd',1,'p_smd','PLY',172),
  ('reg_bloc -> TEXT','reg_bloc',1,'p_reg_bloc','PLY',176),
  ('reg_bloc -> STAR in_bold_italic STAR','reg_bloc',3,'p_reg_bloc','PLY',177),
  ('reg_bloc -> UNDER in_bold_italic UNDER','reg_bloc',3,'p_reg_bloc','PLY',178),
  ('reg_bloc -> LBK smd RBK','reg_bloc',3,'p_reg_bloc','PLY',179),
  ('reg_bloc -> PARAGRAPH','reg_bloc',1,'p_reg_bloc','PLY',180),
  ('reg_bloc -> FUNC LB smd RB','reg_bloc',4,'p_reg_bloc','PLY',181),
  ('reg_bloc -> VAR','reg_bloc',1,'p_reg_bloc','PLY',182),
  ('in_bold_italic -> TEXT','in_bold_italic',1,'p_in_bold_italic','PLY',186),
  ('in_bold_italic -> LBK smd RBK','in_bold_italic',3,'p_in_bold_italic','PLY',187),
  ('in_bold_italic -> PARAGRAPH','in_bold_italic',1,'p_in_bold_italic','PLY',188),
  ('in_bold_italic -> FUNC LB smd RB','in_bold_italic',4,'p_in_bold_italic','PLY',189),
  ('in_bold_italic -> VAR','in_bold_italic',1,'p_in_bold_italic','PLY',190),
]
